export const factoryAbi = [
  {
    type: "function",
    name: "predict",
    stateMutability: "view",
    inputs: [
      { name: "qx", type: "uint256" },
      { name: "qy", type: "uint256" },
      { name: "rpId", type: "string" },
      { name: "origin", type: "string" },
      { name: "allowLocalDevOrigins", type: "bool" },
    ],
    outputs: [{ name: "predicted", type: "address" }],
  },
  {
    type: "function",
    name: "createAccount",
    stateMutability: "nonpayable",
    inputs: [
      { name: "qx", type: "uint256" },
      { name: "qy", type: "uint256" },
      { name: "rpId", type: "string" },
      { name: "origin", type: "string" },
      { name: "allowLocalDevOrigins", type: "bool" },
    ],
    outputs: [{ name: "account", type: "address" }],
  },
] as const;

export const accountAbi = [
  {
    type: "function",
    name: "qx",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "qy",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "nonce",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "rpId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "origin",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "allowLocalDevOrigins",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "challengeFor",
    stateMutability: "view",
    inputs: [
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
      { name: "data", type: "bytes" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "assertionHash",
    stateMutability: "pure",
    inputs: [
      { name: "authenticatorData", type: "bytes" },
      { name: "clientDataJSON", type: "bytes" },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "execute",
    stateMutability: "payable",
    inputs: [
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
      { name: "data", type: "bytes" },
      { name: "deadline", type: "uint256" },
      { name: "authenticatorData", type: "bytes" },
      { name: "clientDataJSON", type: "bytes" },
      { name: "r", type: "uint256" },
      { name: "s", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "error", name: "Expired", inputs: [] },
  { type: "error", name: "BadRecipient", inputs: [] },
  { type: "error", name: "CallFailed", inputs: [] },
  { type: "error", name: "BadKey", inputs: [] },
  { type: "error", name: "BadRpId", inputs: [] },
  { type: "error", name: "BadOrigin", inputs: [] },
  { type: "error", name: "BadAuthenticatorData", inputs: [] },
  { type: "error", name: "UserNotPresent", inputs: [] },
  { type: "error", name: "UserNotVerified", inputs: [] },
  { type: "error", name: "RpIdMismatch", inputs: [] },
  { type: "error", name: "BadClientData", inputs: [] },
  { type: "error", name: "BadClientDataType", inputs: [] },
  { type: "error", name: "OriginMismatch", inputs: [] },
  { type: "error", name: "ChallengeMismatch", inputs: [] },
  { type: "error", name: "CrossOrigin", inputs: [] },
  { type: "error", name: "SignatureInvalid", inputs: [] },
  {
    type: "event",
    name: "Executed",
    inputs: [
      { name: "to", type: "address", indexed: true },
      { name: "value", type: "uint256", indexed: false },
      { name: "nonce", type: "uint256", indexed: true },
      { name: "challenge", type: "bytes32", indexed: false },
    ],
  },
] as const;
